/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-05-17 12:22:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class allLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("*{\r\n");
      out.write("margin:0;\r\n");
      out.write("padding:0;\r\n");
      out.write("box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write(".container{\r\n");
      out.write("height:650px;\r\n");
      out.write("width:100%;\r\n");
      out.write("background-image: url(\"images/alllogin.jpg\");\r\n");
      out.write("background-position: center;\r\n");
      out.write("background-size: cover;\r\n");
      out.write("background-repeat: no-repeat;\r\n");
      out.write("}\r\n");
      out.write(".myside{\r\n");
      out.write("height:80px;\r\n");
      out.write("width:100%;\r\n");
      out.write("}\r\n");
      out.write(".b1{\r\n");
      out.write("height:200px;\r\n");
      out.write("width:80%;\r\n");
      out.write("margin:0 auto;\r\n");
      out.write("display:flex;\r\n");
      out.write("}\r\n");
      out.write(".box1{\r\n");
      out.write("height:250px;\r\n");
      out.write("width:20%;\r\n");
      out.write("margin-left:150px;\r\n");
      out.write("flex:right;\r\n");
      out.write("border:2px solid black;\r\n");
      out.write("background-color:blue;\r\n");
      out.write("border-radius:10vh;\r\n");
      out.write("}\r\n");
      out.write(".box2{\r\n");
      out.write("height:250px;\r\n");
      out.write("width:20%;\r\n");
      out.write("margin-left:300px;\r\n");
      out.write("flex:left;\r\n");
      out.write("border:2px solid black;\r\n");
      out.write("background-color:blue;\r\n");
      out.write("border-radius:10vh;\r\n");
      out.write("}\r\n");
      out.write(".box img{\r\n");
      out.write("height:100px;\r\n");
      out.write("width:40%;\r\n");
      out.write("}\r\n");
      out.write(".box3{\r\n");
      out.write("margin-left:550px;\r\n");
      out.write("height:200px;\r\n");
      out.write("width:200px;\r\n");
      out.write("background-color:blue;\r\n");
      out.write("border:2px solid black;\r\n");
      out.write("border-radius:10vh;\r\n");
      out.write("}\r\n");
      out.write(".box3 img{\r\n");
      out.write("height:200px;\r\n");
      out.write("width:80%;\r\n");
      out.write("}\r\n");
      out.write(".box1 h1{\r\n");
      out.write("margin-left:4vh;\r\n");
      out.write("}\r\n");
      out.write(".box2 h1{\r\n");
      out.write("margin-left:10vh;\r\n");
      out.write("}\r\n");
      out.write(".box3 h1{\r\n");
      out.write("margin-left:50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"myside\">\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"box3\">\r\n");
      out.write("<a href=\"Login.jsp\"><img alt=\"\" src=\"");
      out.print("images/admin1-removebg-preview (1).png");
      out.write("\"></a>\r\n");
      out.write("<h1>Admin</h1>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"b1\">\r\n");
      out.write("<div class=\"box1\">\r\n");
      out.write("<a href=\"ReceptioniestLogin.jsp\"><img alt=\"\" src=\"");
      out.print("images/rec-removebg-preview.png");
      out.write("\"></a>\r\n");
      out.write("<br><br>\r\n");
      out.write("<h1>Receptionist</h1>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"box2\">\r\n");
      out.write("<a href=\"DoctorLogin.jsp\"><img href=\"DoctorLogin.jsp\" src=\"");
      out.print("images/doctor1-removebg-preview.png");
      out.write("\"></a>\r\n");
      out.write("<br><br>\r\n");
      out.write("<h1>Doctor</h1>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
